"""The phrase weights behind :class:`HeuristicClassifier`.

Weights are hand-set, then checked against ``evals/golden_set.jsonl``. Roughly:
1.5+ is a phrase that only appears in one intent ("reset my password"), 1.0-1.4
is strong but shared, below 1.0 is a hint that needs company.

Phrases are matched against text that has been lowercased with apostrophes
removed, so write "hasnt", not "hasn't".
"""

from __future__ import annotations

from ..models import Intent

INTENT_PHRASES: dict[Intent, dict[str, float]] = {
    Intent.ORDER_STATUS: {
        "delivered but": 1.6,
        "no parcel": 1.6,
        "nothing at my door": 1.6,
        "change the delivery address": 1.8,
        "delivery address": 1.5,
        "when will my": 1.4,
        "arrive": 1.1,
        "dispatch": 1.2,
        "where is my order": 1.8,
        "wheres my order": 1.8,
        "order status": 1.7,
        "status of my order": 1.7,
        "track my": 1.5,
        "tracking number": 1.6,
        "tracking info": 1.5,
        "when will it arrive": 1.6,
        "when will my order": 1.6,
        "delivery date": 1.4,
        "out for delivery": 1.4,
        "hasnt arrived": 1.5,
        "hasnt shipped": 1.5,
        "never arrived": 1.5,
        "still waiting for my": 1.2,
        "shipment": 1.1,
        "package": 1.0,
        "shipped yet": 1.4,
        "delayed": 0.8,
        "order number": 0.7,
        "estimated delivery": 1.4,
    },
    Intent.RETURNS_REFUND: {
        "send back": 1.5,
        "return something": 1.7,
        "to return": 1.4,
        "arrived cracked": 1.6,
        "arrived damaged": 1.6,
        "arrived broken": 1.6,
        "replacement": 1.3,
        "how long do i have": 1.3,
        "refund": 1.5,
        "return it": 1.5,
        "return this": 1.5,
        "send it back": 1.6,
        "return label": 1.7,
        "return policy": 1.6,
        "money back": 1.7,
        "exchange it": 1.4,
        "cancel my order": 2.5,
        "rma": 1.4,
        "restocking fee": 1.5,
        "doesnt fit": 1.2,
        "changed my mind": 1.3,
        "wrong item": 1.4,
        "return window": 1.6,
        "start a return": 1.8,
    },
    Intent.BILLING: {
        "payment fails": 1.7,
        "subscription payment": 1.6,
        "renewed my": 1.6,
        "without asking": 0.8,
        "charged me": 1.5,
        "double charged": 1.9,
        "charged twice": 1.9,
        "overcharged": 1.8,
        "unauthorized charge": 1.9,
        "invoice": 1.4,
        "receipt": 1.2,
        "billing": 1.4,
        "billed": 1.4,
        "my card": 1.1,
        "credit card": 1.1,
        "payment method": 1.4,
        "payment failed": 1.5,
        "declined": 1.2,
        "renewal charge": 1.6,
        "charge on my": 1.6,
        "sales tax": 1.2,
        "update my card": 1.6,
    },
    Intent.ACCOUNT_ACCESS: {
        "no account": 1.7,
        "account with my email": 1.8,
        "email on my account": 1.8,
        "email address on the account": 1.7,
        "cant get into my account": 2.0,
        "cant access my account": 2.0,
        "get into my account": 1.7,
        "cant get in": 1.6,
        "log in": 1.3,
        "sign in": 1.3,
        "cant log in": 1.9,
        "cant login": 1.9,
        "cant sign in": 1.9,
        "log into my account": 1.6,
        "password": 1.6,
        "reset my password": 1.9,
        "forgot my password": 1.9,
        "locked out": 1.8,
        "two factor": 1.6,
        "2fa": 1.6,
        "verification code": 1.5,
        "authentication code": 1.5,
        "username": 1.3,
        "account access": 1.4,
        "change my email": 1.3,
    },
    Intent.TECHNICAL_ISSUE: {
        "live view": 1.6,
        "black screen": 1.8,
        "never loads": 1.5,
        "battery only lasts": 1.8,
        "battery lasts": 1.6,
        "offline": 1.6,
        "disconnect": 1.5,
        "reconnect": 1.4,
        "keeps going": 1.3,
        "wont stay": 1.5,
        "stopped working": 1.5,
        "keeps freezing": 1.6,
        "unplug": 1.3,
        "reboot": 1.2,
        "signal strength": 1.4,
        "not working": 1.3,
        "wont connect": 1.8,
        "wont turn on": 1.8,
        "keeps disconnecting": 1.8,
        "keeps dropping": 1.6,
        "goes offline": 1.7,
        "shows offline": 1.7,
        "app crashes": 1.8,
        "app keeps": 1.4,
        "error message": 1.3,
        "firmware": 1.5,
        "wifi": 1.3,
        "factory reset": 1.4,
        "blinking red": 1.5,
        "no video": 1.5,
        "no live feed": 1.6,
        "wont pair": 1.7,
        "troubleshoot": 1.5,
        "not recording": 1.6,
        "battery drains": 1.6,
        "motion alerts": 1.2,
        "night vision is": 1.2,
        "setup": 0.7,
    },
    Intent.CANCELLATION: {
        "stop being billed": 1.9,
        "pause my plan": 1.9,
        "pause my subscription": 1.9,
        "cancel my subscription": 2.0,
        "cancel my plan": 2.0,
        "cancel my account": 1.9,
        "cancel my membership": 2.0,
        "close my account": 1.8,
        "delete my account": 1.7,
        "stop billing me": 1.7,
        "stop charging me": 1.7,
        "dont want to renew": 1.7,
        "do not renew": 1.7,
        "end my subscription": 1.9,
        "unsubscribe": 1.3,
        "downgrade": 1.1,
        "cancel": 0.8,
    },
    Intent.PRODUCT_INFO: {
        "how much is": 1.4,
        "family plan": 1.5,
        "paid plan": 1.6,
        "do i need a": 1.2,
        "two way talk": 1.3,
        "outdoors": 1.3,
        "rtsp": 1.7,
        "waterproof": 1.5,
        "does it work with": 1.7,
        "is it compatible": 1.8,
        "compatible with": 1.6,
        "whats the difference": 1.7,
        "difference between": 1.6,
        "which model": 1.5,
        "do you sell": 1.5,
        "in stock": 1.3,
        "before i buy": 1.7,
        "thinking of buying": 1.7,
        "how much does": 1.2,
        "field of view": 1.4,
        "how long does the battery last": 1.6,
        "storage plan": 1.2,
        "does it support": 1.6,
        "specs": 1.3,
    },
    Intent.COMPLAINT: {
        "your support is": 1.5,
        "is somehow worse": 1.5,
        "garbage": 1.5,
        "file a complaint": 2.0,
        "formal complaint": 2.0,
        "unacceptable": 1.6,
        "ridiculous": 1.4,
        "absolutely terrible": 1.6,
        "worst": 1.4,
        "my lawyer": 2.0,
        "legal action": 2.0,
        "sue you": 1.9,
        "better business bureau": 1.9,
        "chargeback": 1.6,
        "third time": 1.5,
        "nobody has called": 1.7,
        "no one has called": 1.7,
        "called me back": 1.5,
        "gotten back to me": 1.6,
        "got back to me": 1.5,
        "fourth time": 1.6,
        "nobody has gotten back": 1.7,
        "no one has responded": 1.7,
        "still no response": 1.5,
        "fed up": 1.5,
        "this is a scam": 1.7,
        "leave a review": 1.2,
    },
}

#: Phrases that mean "stop talking to me, robot". Any hit forces a handoff
#: regardless of how confident the classifier is about the intent.
HUMAN_REQUEST_PHRASES: tuple[str, ...] = (
    "agent",
    "get me a person",
    "get me a human",
    "get me someone",
    "person please",
    "human please",
    "actual person",
    "real human",
    "speak with a human",
    "speak with someone",
    "talk with someone",
    "customer service",
    "speak to a human",
    "talk to a human",
    "speak to a person",
    "real person",
    "speak to someone",
    "talk to someone",
    "speak to an agent",
    "talk to an agent",
    "live agent",
    "human agent",
    "customer service rep",
    "representative",
    "supervisor",
    "your manager",
    "speak to a manager",
    "operator",
    "transfer me",
    "put me through",
    "stop the bot",
    "not a robot",
    "im done with this bot",
)

ANGRY_TERMS: tuple[str, ...] = (
    "furious",
    "ridiculous",
    "appalling",
    "shambles",
    "outrageous",
    "unacceptable",
    "disgusted",
    "absolutely ridiculous",
    "worst",
    "hell",
    "damn",
    "sick of",
    "fed up",
    "scam",
    "stealing",
    "lawyer",
    "sue",
    "never buying",
    "garbage",
    "useless",
)

FRUSTRATED_TERMS: tuple[str, ...] = (
    "frustrated",
    "still waiting",
    "waiting for over",
    "annoyed",
    "disappointed",
    "again",
    "still not",
    "still no",
    "third time",
    "fourth time",
    "keeps happening",
    "waited",
    "no one",
    "nobody",
    "over a week",
    "two weeks",
    "unhappy",
    "not happy",
    "come on",
    "seriously",
)

POSITIVE_TERMS: tuple[str, ...] = (
    "thank you",
    "thanks",
    "appreciate",
    "great",
    "love the",
    "works perfectly",
    "happy with",
    "awesome",
    "excellent",
    "no rush",
    "please and thank",
)
